language: python
dist: xenial

python:
  - 3.4

env:
  - DJANGO="Django>=2.0,<2.1"
  - DJANGO="Django>=1.11,<2"
  - DJANGO="Django>=1.10,<1.11"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.7,<1.8"

install:
  - pip install $DJANGO
  - pip install django-redis
  - pip install six

script:
  - python tests/run_tests.py

services:
  - redis-server
