language: python
dist: xenial

python:
  - 3.5
  - 3.4
  - 2.7

env:
  - DJANGO="Django>=2.0,<2.1"
  - DJANGO="Django>=1.11,<2"
  - DJANGO="Django>=1.10,<1.11"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.7,<1.8"

install:
  - pip install $DJANGO
  - pip install django-redis
  - pip install six

script:
  - python tests/run_tests.py

services:
  - redis-server

matrix:

  include:
   - python: 3.8
     env: DJANGO="Django>=2.0,<2.1"
   - python: 3.8
     env: DJANGO="Django>=2.1,<2.2"
   - python: 3.8
     env: DJANGO="Django>=2.2,<2.3"
   - python: 3.8
     env: DJANGO="Django>=3.0,<3.1 git+https://github.com/niwinz/django-redis"
     
   - python: 3.7
     env: DJANGO="Django>=1.11,<2"
   - python: 3.7
     env: DJANGO="Django>=2.0,<2.1"
   - python: 3.7
     env: DJANGO="Django>=2.1,<2.2"
   - python: 3.7
     env: DJANGO="Django>=2.2,<2.3"
   - python: 3.7
     env: DJANGO="Django>=3.0,<3.1 git+https://github.com/niwinz/django-redis"
     
   - python: 3.6
     env: DJANGO="Django>=1.11,<2"
   - python: 3.6
     env: DJANGO="Django>=2.0,<2.1"
   - python: 3.6
     env: DJANGO="Django>=2.1,<2.2"
   - python: 3.6
     env: DJANGO="Django>=2.2,<2.3"
   - python: 3.6
     env: DJANGO="Django>=3.0,<3.1 git+https://github.com/niwinz/django-redis"

  exclude:
   - python: 3.5
     env: DJANGO="Django>=1.7,<1.8"

   - python: 2.7
     env: DJANGO="Django>=2.0,<2.1"
